UPDATE alunos
SET Cidade = CASE
    WHEN id = 1 THEN 'Sumaré'
    WHEN id = 2 THEN 'Campinas'
    WHEN id = 3 THEN 'Nova Odessa'
	WHEN id = 4 THEN 'Americana'
    WHEN id = 5 THEN 'Santa Bárbara'
    WHEN id = 6 THEN 'Hortolândia'
    WHEN id = 7 THEN 'Sorocaba'
    WHEN id = 8 THEN 'Cosmópolis'
    WHEN id = 9 THEN 'Águas de São Pedro'
	WHEN id = 10 THEN 'São Pedro'
    WHEN id = 11 THEN 'Santa Maria da Serra'
    WHEN id = 12 THEN 'Piracicaba'
    WHEN id = 13 THEN 'Sumaré'
    WHEN id = 14 THEN 'Campinas'
    WHEN id = 15 THEN 'Nova Odessa'
	WHEN id = 16 THEN 'Americana'
    WHEN id = 17 THEN 'Santa Bárbara'
    WHEN id = 18 THEN 'Hortolândia'
    WHEN id = 19 THEN 'Sorocaba'
    WHEN id = 20 THEN 'Cosmópolis'
    WHEN id = 21 THEN 'Águas de São Pedro'
	WHEN id = 22 THEN 'Piracicaba'
    WHEN id = 23 THEN 'Sumaré'
    WHEN id = 24 THEN 'Campinas'
    WHEN id = 25 THEN 'Nova Odessa'
    WHEN id = 26 THEN 'Americana'
    WHEN id = 27 THEN 'Santa Bárbara'
	WHEN id = 28 THEN 'Hortolândia'
    WHEN id = 29 THEN 'Sorocaba'
    WHEN id = 30 THEN 'Cosmópolis'
    WHEN id = 31 THEN 'Águas de São Pedro'
    WHEN id = 32 THEN 'Nova Odessa'
    WHEN id = 33 THEN 'Piracicaba'
	WHEN id = 34 THEN 'Sumaré'
    ELSE Cidade
END
